# Generated by Django 2.2.14 on 2021-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bobaproduct_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='toppings',
            field=models.CharField(choices=[('YES', 'Boba'), ('NO', 'No Boba')], max_length=200, null=True),
        ),
    ]
