# Generated by Django 2.2.14 on 2021-05-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_order_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Order',
            new_name='CustomerOrder',
        ),
    ]
