# Generated by Django 2.2.14 on 2021-05-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210513_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobaproduct',
            name='description',
        ),
    ]
