# Generated by Django 2.2.14 on 2021-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_bobaproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobaproduct',
            name='image',
            field=models.ImageField(default="{% static 'images/filler.jpg' %}", upload_to='boba'),
        ),
    ]
