# Generated by Django 2.2.14 on 2021-05-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210513_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='toppings',
        ),
    ]
